nelmio_api_doc:
    documentation:
        info:
            title: Geotensions API
            description: API REST exploitant ACLED pour visualisation cartographique.
            version: 0.2.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
