nelmio_api_doc:
    documentation:
        info:
            title: GeoTensions API
            description: REST API serving filtered ACLED data as GeoJSON.

            version: 0.2.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
